"""AgentBench scanner — generate test files from detected behaviors."""

from __future__ import annotations

import re

from agentbench.scanner.analyzer import DetectedBehavior

# Mapping from test_type to the assertion pattern used in generated code.
ASSERTION_MAP: dict[str, str] = {
    "refusal": "expect(trajectory).to_refuse()",
    "response_contains": "expect(trajectory).to_respond_with({expected!r})",
    "response_not_contains": "expect(trajectory).to_not_expose({expected!r})",
    "response_length": "# Response length check: assert len(trajectory.final_response) > 0",
    "language": "# Language check: assert response is in expected language",
    "consistency": "# Consistency: call twice, compare responses",
    "error_handling": "expect(trajectory).to_have_no_errors()",
    "tool_usage": "# Tool usage check: assert specific tools were used",
}


def _sanitize_method_name(description: str, index: int) -> str:
    """Turn a behavior description into a valid Python method name."""
    # Remove non-alphanumeric chars, lowercase, collapse spaces
    name = re.sub(r"[^a-zA-Z0-9\s_]", "", description).strip().lower()
    name = re.sub(r"[\s]+", "_", name)
    # Truncate
    name = name[:50]
    # Ensure it doesn't start with a digit
    if name and name[0].isdigit():
        name = f"test_{name}"
    # Fallback
    if not name or name == "_":
        name = f"detected_behavior_{index}"
    return f"test_{name}"


class TestGenerator:
    """Generate a Python test file from a list of DetectedBehavior objects.

    The generated file:
    - Imports AgentTest and expect from agentbench
    - Defines a class that extends AgentTest
    - Each DetectedBehavior becomes a test method
    - Uses proper assertions mapped by test_type
    - Includes comments showing what was auto-detected
    - Is syntactically valid Python (verified with compile())
    """

    # Prevent pytest from trying to collect this as a test class
    __test__ = False

    def __init__(self, class_name: str = "AutoGeneratedTests") -> None:
        self.class_name = class_name

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, behaviors: list[DetectedBehavior]) -> str:
        """Return a complete Python test file as a string.

        The output is guaranteed to be syntactically valid Python — the
        method raises ``SyntaxError`` if code generation produces something
        that ``compile()`` cannot parse.
        """
        header = self._generate_header()
        methods = "\n".join(self.generate_test_method(b, idx) for idx, b in enumerate(behaviors))

        code = f"""\
{header}
class {self.class_name}(AgentTest):
    \"\"\"Auto-generated test suite — produced by agentbench scan.

    DO NOT EDIT MANUALLY. Re-run `agentbench scan` to regenerate.
    \"\"\"

{methods}
"""
        # Verify the generated code is valid Python
        compile(code, "<generated-test>", "exec")
        return code

    def generate_test_method(
        self,
        behavior: DetectedBehavior,
        index: int = 0,
    ) -> str:
        """Return a single test method as a string."""
        method_name = _sanitize_method_name(behavior.description, index)

        lines = [
            f"    # Auto-detected: {behavior.description}",
            f"    # Category: {behavior.category} | Confidence: {behavior.confidence:.2f}",
            f"    def {method_name}(self):",
            f'        """{behavior.description}"""',
        ]

        if behavior.test_type == "consistency":
            # Consistency tests call self.run() twice
            lines.append(f"        t1 = self.run({behavior.test_prompt!r})")
            lines.append(f"        t2 = self.run({behavior.test_prompt!r})")
            lines.append("        # assert responses are semantically similar")
        elif behavior.test_type == "error_handling":
            lines.append(f"        trajectory = self.run({behavior.test_prompt!r})")
            lines.append("        expect(trajectory).to_have_no_errors()")
        elif behavior.test_type == "refusal":
            lines.append(f"        trajectory = self.run({behavior.test_prompt!r})")
            lines.append("        expect(trajectory).to_refuse()")
        elif behavior.test_type == "response_contains":
            lines.append(f"        trajectory = self.run({behavior.test_prompt!r})")
            lines.append(f"        expect(trajectory).to_respond_with({behavior.expected!r})")
        elif behavior.test_type == "response_not_contains":
            lines.append(f"        trajectory = self.run({behavior.test_prompt!r})")
            lines.append(f"        expect(trajectory).to_not_expose({behavior.expected!r})")
        elif behavior.test_type == "response_length":
            lines.append(f"        trajectory = self.run({behavior.test_prompt!r})")
            lines.append(
                '        assert trajectory.final_response.strip(), "Expected non-empty response"'
            )
        elif behavior.test_type == "language":
            lines.append(f"        trajectory = self.run({behavior.test_prompt!r})")
            lines.append(
                '        assert trajectory.final_response.strip(), "Expected non-empty response"'
            )
        elif behavior.test_type == "tool_usage":
            lines.append(f"        trajectory = self.run({behavior.test_prompt!r})")
            lines.append(f"        # tool_usage: {behavior.expected!r}")
        else:
            # Fallback for unknown types
            lines.append(f"        trajectory = self.run({behavior.test_prompt!r})")
            lines.append(
                f"        # Unknown test_type: {behavior.test_type!r}"
                f", expected: {behavior.expected!r}"
            )

        lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_header(self) -> str:
        """Return the file header with imports."""
        return (
            '"""Auto-generated by agentbench scan — DO NOT EDIT."""\n'
            "\n"
            "from agentbench import AgentTest, expect\n"
        )

    def _build_assertion(self, behavior: DetectedBehavior, method_name: str) -> str:
        """Return the assertion line for a given test_type."""
        test_type = behavior.test_type

        if test_type == "refusal":
            return "expect(trajectory).to_refuse()"
        elif test_type == "response_contains":
            return f"expect(trajectory).to_respond_with({behavior.expected!r})"
        elif test_type == "response_not_contains":
            return f"expect(trajectory).to_not_expose({behavior.expected!r})"
        elif test_type == "error_handling":
            return "expect(trajectory).to_have_no_errors()"
        elif test_type == "response_length":
            return 'assert trajectory.final_response.strip(), "Expected non-empty response"'
        elif test_type == "language":
            return 'assert trajectory.final_response.strip(), "Expected non-empty response"'
        elif test_type == "consistency":
            return "# consistency check"
        elif test_type == "tool_usage":
            return f"# tool_usage: {behavior.expected!r}"
        else:
            return f"# unknown test_type: {test_type!r}"
