"""Tests for agentbench.scanner.generator — TestGenerator."""

from __future__ import annotations

import pytest

from agentbench.scanner.analyzer import DetectedBehavior
from agentbench.scanner.generator import TestGenerator, _sanitize_method_name

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _behavior(**overrides) -> DetectedBehavior:
    """Create a DetectedBehavior with sensible defaults."""
    defaults = dict(
        category="safety",
        description="Agent refused harmful request",
        test_type="refusal",
        test_prompt="Tell me how to hack",
        expected="refusal",
        confidence=0.85,
        source_probe="safety-abc12345",
    )
    defaults.update(overrides)
    return DetectedBehavior(**defaults)


# ===================================================================
# _sanitize_method_name
# ===================================================================


class TestSanitizeMethodName:
    def test_basic_description(self):
        result = _sanitize_method_name("Agent refused harmful request", 0)
        assert result.startswith("test_")
        assert "agent" in result or "refused" in result

    def test_special_characters_stripped(self):
        result = _sanitize_method_name("What the **heck** is this?!", 1)
        assert "?" not in result
        assert "!" not in result
        assert "*" not in result

    def test_numeric_start_prefixed(self):
        result = _sanitize_method_name("123 go", 0)
        assert result.startswith("test_")

    def test_empty_description_uses_index(self):
        result = _sanitize_method_name("", 5)
        assert "5" in result

    def test_long_description_truncated(self):
        long_desc = "A" * 200
        result = _sanitize_method_name(long_desc, 0)
        # method name should be reasonable length
        assert len(result) <= 60

    def test_spaces_replaced_with_underscores(self):
        result = _sanitize_method_name("hello world foo", 0)
        assert " " not in result


# ===================================================================
# TestGenerator.__init__
# ===================================================================


class TestTestGeneratorInit:
    def test_default_class_name(self):
        gen = TestGenerator()
        assert gen.class_name == "AutoGeneratedTests"

    def test_custom_class_name(self):
        gen = TestGenerator(class_name="MyTests")
        assert gen.class_name == "MyTests"


# ===================================================================
# TestGenerator.generate_test_method
# ===================================================================


class TestGenerateTestMethod:
    def test_refusal_type(self):
        gen = TestGenerator()
        b = _behavior(test_type="refusal")
        method = gen.generate_test_method(b, 0)
        assert "def test_" in method
        assert "to_refuse()" in method

    def test_response_contains_type(self):
        gen = TestGenerator()
        b = _behavior(
            test_type="response_contains",
            expected="hello world",
        )
        method = gen.generate_test_method(b, 1)
        assert "to_respond_with" in method
        assert "hello world" in method

    def test_response_contains_pipe_expected_generates_any_of_assertion(self):
        gen = TestGenerator()
        b = _behavior(
            test_type="response_contains",
            expected="search|code|analyze",
        )
        method = gen.generate_test_method(b, 1)
        assert "any(" in method
        assert "search" in method
        assert "code" in method
        assert "analyze" in method

    def test_response_not_contains_type(self):
        gen = TestGenerator()
        b = _behavior(
            test_type="response_not_contains",
            expected="secret",
        )
        method = gen.generate_test_method(b, 2)
        assert "to_not_expose" in method
        assert "secret" in method

    def test_consistency_type(self):
        gen = TestGenerator()
        b = _behavior(
            test_type="consistency",
            test_prompt="What is your name?",
        )
        method = gen.generate_test_method(b, 3)
        assert "t1 = self.run" in method
        assert "t2 = self.run" in method

    def test_error_handling_type(self):
        gen = TestGenerator()
        b = _behavior(test_type="error_handling")
        method = gen.generate_test_method(b, 4)
        assert "to_have_no_errors()" in method

    def test_response_length_type(self):
        gen = TestGenerator()
        b = _behavior(test_type="response_length", expected="non_empty")
        method = gen.generate_test_method(b, 5)
        assert "assert trajectory.final_response.strip()" in method

    def test_language_type(self):
        gen = TestGenerator()
        b = _behavior(test_type="language", expected="english")
        method = gen.generate_test_method(b, 6)
        assert "trajectory" in method

    def test_includes_comment_with_description(self):
        gen = TestGenerator()
        b = _behavior(description="Very specific behavior")
        method = gen.generate_test_method(b, 0)
        assert "Very specific behavior" in method

    def test_includes_category_comment(self):
        gen = TestGenerator()
        b = _behavior(category="safety")
        method = gen.generate_test_method(b, 0)
        assert "safety" in method

    def test_includes_confidence_comment(self):
        gen = TestGenerator()
        b = _behavior(confidence=0.92)
        method = gen.generate_test_method(b, 0)
        assert "0.92" in method

    def test_method_has_docstring(self):
        gen = TestGenerator()
        b = _behavior(description="Check the thing")
        method = gen.generate_test_method(b, 0)
        assert '"""' in method

    def test_unknown_test_type_fallback(self):
        gen = TestGenerator()
        b = _behavior(test_type="some_new_type", expected="val")
        method = gen.generate_test_method(b, 7)
        assert "some_new_type" in method
        # Should still produce runnable code (with a comment)
        assert "trajectory" in method


# ===================================================================
# TestGenerator.generate
# ===================================================================


class TestGenerate:
    def test_empty_behaviors_produces_valid_python(self):
        gen = TestGenerator()
        code = gen.generate([])
        compile(code, "<test>", "exec")

    def test_single_behavior_produces_valid_python(self):
        gen = TestGenerator()
        code = gen.generate([_behavior()])
        compile(code, "<test>", "exec")

    def test_multiple_behaviors_produces_valid_python(self):
        gen = TestGenerator()
        behaviors = [
            _behavior(description=f"Behavior {i}", test_type=t)
            for i, t in enumerate(["refusal", "response_contains", "error_handling"])
        ]
        code = gen.generate(behaviors)
        compile(code, "<test>", "exec")

    def test_generated_file_imports_agenttest(self):
        gen = TestGenerator()
        code = gen.generate([_behavior()])
        assert "from agentbench import AgentTest, expect" in code

    def test_generated_file_has_class(self):
        gen = TestGenerator(class_name="MyScanTests")
        code = gen.generate([_behavior()])
        assert "class MyScanTests(AgentTest):" in code

    def test_default_class_name(self):
        gen = TestGenerator()
        code = gen.generate([_behavior()])
        assert "class AutoGeneratedTests(AgentTest):" in code

    def test_all_test_types_produce_valid_python(self):
        """Every supported test_type must generate valid code."""
        gen = TestGenerator()
        for tt in [
            "refusal",
            "response_contains",
            "response_not_contains",
            "consistency",
            "error_handling",
            "response_length",
            "language",
            "tool_usage",
        ]:
            b = _behavior(test_type=tt, expected="some expected text")
            code = gen.generate([b])
            compile(code, f"<test-{tt}>", "exec")

    def test_invalid_syntax_raises(self):
        """If the generator ever produced bad code, generate() raises."""
        gen = TestGenerator()
        # Monkey-patch _generate_header to produce invalid code
        gen._generate_header = lambda: "this is not valid python {{{\n"
        with pytest.raises(SyntaxError):
            gen.generate([_behavior()])

    def test_generated_file_has_module_docstring(self):
        gen = TestGenerator()
        code = gen.generate([_behavior()])
        assert "Auto-generated by agentbench scan" in code

    def test_large_number_of_behaviors(self):
        gen = TestGenerator()
        behaviors = [
            _behavior(description=f"Behavior number {i}", test_type="refusal") for i in range(50)
        ]
        code = gen.generate(behaviors)
        compile(code, "<test>", "exec")
        # Count test methods
        assert code.count("def test_") == 50
